#!/bin/bash

mkdir build

# Copiar todas las imágenes
find -type f \! -name '*.md' -print0 | xargs -0 cp -t build/

# Metadata
cat > build/book.md <<EOT
% Manual de Cryptoparty
% Traducción del Partido Pirata de Argentina
% $(date +"%B, %Y")

EOT

# Concatenar todos los artículos
cat ../README.md $(find -name '*.md' | sort | grep -v "book\.md") >> build/book.md

pushd build

# Convertir!
echo ":: Generando LaTeX"
[ ! -f book.tex ] &&
pandoc -V documentclass=book \
       -V fontsize=10pt,a5paper,twoside \
       -V geometry=hcentering \
       -V geometry=bindingoffset=1cm \
       -V lang=spanish \
       -V links-as-notes \
       --include-in-header=header.tex \
       --latex-engine=xelatex \
       --table-of-contents \
       -t latex \
       -o book.tex \
       book.md

echo ":: Generando PDF"
[ ! -f CryptoHandbook.pdf ] &&
pandoc -V documentclass=book \
       -V fontsize=10pt,a5paper,twoside \
       -V geometry=hcentering \
       -V geometry=bindingoffset=1cm \
       -V lang=spanish \
       -V links-as-notes \
       --include-in-header=header.tex \
       --latex-engine=xelatex \
       --table-of-contents \
       -o CryptoHandbook.pdf \
       book.tex

echo ":: Generando EPUB"
[ ! -f CryptoHandbook.epub ] &&
pandoc -V lang=spanish \
       -o CryptoHandbook.epub \
       book.md

echo ":: Generando torrent"
[ ! -f CryptoHandbook.pdf.torrent ] &&
mktorrent -a udp://tracker.publicbt.com:80 \
          --verbose \
          CryptoHandbook.pdf 

[ ! -f CryptoHandbook.epub.torrent ] &&
mktorrent -a udp://tracker.publicbt.com:80 \
          --verbose \
          CryptoHandbook.epub

popd
